var nome = document.querySelector("#exampleInputName")
console.log(nome)
var gender = document.querySelectorAll("form#form-user-create [name=gender]:checked")
console.log(gender)
var dateNasc = document.querySelector("#exampleInputBirth")
console.log(dateNasc)
var country = document.querySelector("#exampleInputCountry")
console.log(country)
var email = document.querySelector("#exampleInputEmail1")
console.log(email)
var password = document.querySelector("#exampleInputPassword1")
console.log(password)
var photo = document.querySelector("#exampleInputFile")
console.log(photo)
var admin = document.querySelector("#adm")
console.log(admin)
